
function_body_length: 100

line_length:
  warning: 120
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true

type_name:
    min_length: 2
    max_length: 50

identifier_name:
    min_length: 2
    max_length:
        warning: 90
        error: 1000
    excluded:
        - id
        - i
        - a
        - b
        - l
        - r
    validates_start_with_lowercase: false

disabled_rules: # rule identifiers to exclude from running
- large_tuple
- valid_ibinspectable
- implicit_getter
- superfluous_disable_command


excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Resources
  - Design Pattern Template
  - Pods
